// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Eventos.IO.TestesAutomatizados.CadastroOrganizador
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CadastroDeOrganizadorFeature : Xunit.IClassFixture<CadastroDeOrganizadorFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CadastroDeOrganizadorfeature.feature"
#line hidden
        
        public CadastroDeOrganizadorFeature(CadastroDeOrganizadorFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Cadastro de Organizador", "\tUm organizador fará seu cadastro pelo site\r\n\tpara poder gerenciar seus próprios " +
                    "eventos\r\n\tAo terminar o cadastro receberá uma notificação\r\n\tde sucesso ou de fal" +
                    "ha.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Sucesso")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroDeOrganizadorComSucesso")]
        public virtual void CadastroDeOrganizadorComSucesso()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Sucesso", new string[] {
                        "TesteAutomatizadoCadastroDeOrganizadorComSucesso"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 11
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table1.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table1.AddRow(new string[] {
                        "cpf",
                        "30390600822"});
            table1.AddRow(new string[] {
                        "email",
                        "contato@eduardopires.net.br"});
            table1.AddRow(new string[] {
                        "senha",
                        "Teste@123"});
            table1.AddRow(new string[] {
                        "senhaConfirmacao",
                        "Teste@123"});
#line 12
 testRunner.And("preenche os campos com os valores", ((string)(null)), table1, "E ");
#line 19
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 20
 testRunner.Then("Será registrado e redirecionado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com CPF já utilizado")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroOrganizadorFalha")]
        public virtual void CadastroDeOrganizadorComCPFJaUtilizado()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com CPF já utilizado", new string[] {
                        "TesteAutomatizadoCadastroOrganizadorFalha"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 26
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table2.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table2.AddRow(new string[] {
                        "cpf",
                        "30390600822"});
            table2.AddRow(new string[] {
                        "email",
                        "contato12@eduardopires.net.br"});
            table2.AddRow(new string[] {
                        "senha",
                        "Teste@123"});
            table2.AddRow(new string[] {
                        "senhaConfirmacao",
                        "Teste@123"});
#line 27
 testRunner.And("preenche os campos com os valores", ((string)(null)), table2, "E ");
#line 34
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 35
 testRunner.Then("Recebe uma mensagem de erro de CPF já cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Email já utilizado")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroOrganizadorFalha")]
        public virtual void CadastroDeOrganizadorComEmailJaUtilizado()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Email já utilizado", new string[] {
                        "TesteAutomatizadoCadastroOrganizadorFalha"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 41
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table3.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table3.AddRow(new string[] {
                        "cpf",
                        "30390600821"});
            table3.AddRow(new string[] {
                        "email",
                        "contato@eduardopires.net.br"});
            table3.AddRow(new string[] {
                        "senha",
                        "Teste@123"});
            table3.AddRow(new string[] {
                        "senhaConfirmacao",
                        "Teste@123"});
#line 42
 testRunner.And("preenche os campos com os valores", ((string)(null)), table3, "E ");
#line 49
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 50
 testRunner.Then("recebe uma mensagem de erro de email já cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Senha sem números")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroOrganizadorFalha")]
        public virtual void CadastroDeOrganizadorComSenhaSemNumeros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Senha sem números", new string[] {
                        "TesteAutomatizadoCadastroOrganizadorFalha"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 56
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table4.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table4.AddRow(new string[] {
                        "cpf",
                        "30390600822"});
            table4.AddRow(new string[] {
                        "email",
                        "contato@eduardopires.net.br"});
            table4.AddRow(new string[] {
                        "senha",
                        "Teste@"});
            table4.AddRow(new string[] {
                        "senhaConfirmacao",
                        "Teste@"});
#line 57
 testRunner.And("preenche os campos com os valores", ((string)(null)), table4, "E ");
#line 64
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 65
 testRunner.Then("Recebe uma mensagem de erro de que a senha requer numero", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Senha sem Maiuscula")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroOrganizadorFalha")]
        public virtual void CadastroDeOrganizadorComSenhaSemMaiuscula()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Senha sem Maiuscula", new string[] {
                        "TesteAutomatizadoCadastroOrganizadorFalha"});
#line 69
this.ScenarioSetup(scenarioInfo);
#line 70
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 71
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table5.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table5.AddRow(new string[] {
                        "cpf",
                        "30390600822"});
            table5.AddRow(new string[] {
                        "email",
                        "contato@eduardopires.net.br"});
            table5.AddRow(new string[] {
                        "senha",
                        "teste@123"});
            table5.AddRow(new string[] {
                        "senhaConfirmacao",
                        "teste@123"});
#line 72
 testRunner.And("preenche os campos com os valores", ((string)(null)), table5, "E ");
#line 79
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 80
 testRunner.Then("Recebe uma mensagem de erro de que a senha requer letra maiuscula", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Senha sem minuscula")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroOrganizadorFalha")]
        public virtual void CadastroDeOrganizadorComSenhaSemMinuscula()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Senha sem minuscula", new string[] {
                        "TesteAutomatizadoCadastroOrganizadorFalha"});
#line 84
this.ScenarioSetup(scenarioInfo);
#line 85
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 86
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table6.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table6.AddRow(new string[] {
                        "cpf",
                        "30390600822"});
            table6.AddRow(new string[] {
                        "email",
                        "contato@eduardopires.net.br"});
            table6.AddRow(new string[] {
                        "senha",
                        "TESTE@123"});
            table6.AddRow(new string[] {
                        "senhaConfirmacao",
                        "TESTE@123"});
#line 87
 testRunner.And("preenche os campos com os valores", ((string)(null)), table6, "E ");
#line 94
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 95
 testRunner.Then("Recebe uma mensagem de erro de que a senha requer letra minuscula", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Senha sem caracter especial")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroOrganizadorFalha")]
        public virtual void CadastroDeOrganizadorComSenhaSemCaracterEspecial()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Senha sem caracter especial", new string[] {
                        "TesteAutomatizadoCadastroOrganizadorFalha"});
#line 99
this.ScenarioSetup(scenarioInfo);
#line 100
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 101
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table7.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table7.AddRow(new string[] {
                        "cpf",
                        "30390600822"});
            table7.AddRow(new string[] {
                        "email",
                        "contato@eduardopires.net.br"});
            table7.AddRow(new string[] {
                        "senha",
                        "Teste123"});
            table7.AddRow(new string[] {
                        "senhaConfirmacao",
                        "Teste123"});
#line 102
 testRunner.And("preenche os campos com os valores", ((string)(null)), table7, "E ");
#line 109
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 110
 testRunner.Then("Recebe uma mensagem de erro de que a senha requer caracter especial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Senha em tamanho inferior ao permitido")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroOrganizadorFalha")]
        public virtual void CadastroDeOrganizadorComSenhaEmTamanhoInferiorAoPermitido()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Senha em tamanho inferior ao permitido", new string[] {
                        "TesteAutomatizadoCadastroOrganizadorFalha"});
#line 114
this.ScenarioSetup(scenarioInfo);
#line 115
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 116
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table8.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table8.AddRow(new string[] {
                        "cpf",
                        "30390600822"});
            table8.AddRow(new string[] {
                        "email",
                        "contato@eduardopires.net.br"});
            table8.AddRow(new string[] {
                        "senha",
                        "Te123"});
            table8.AddRow(new string[] {
                        "senhaConfirmacao",
                        "Te123"});
#line 117
 testRunner.And("preenche os campos com os valores", ((string)(null)), table8, "E ");
#line 124
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 125
 testRunner.Then("Recebe uma mensagem de erro de que a senha esta em tamanho inferior ao permitido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Senha diferentes")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroOrganizadorFalha")]
        public virtual void CadastroDeOrganizadorComSenhaDiferentes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Senha diferentes", new string[] {
                        "TesteAutomatizadoCadastroOrganizadorFalha"});
#line 129
this.ScenarioSetup(scenarioInfo);
#line 130
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 131
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table9.AddRow(new string[] {
                        "nome",
                        "Eduardo Pires"});
            table9.AddRow(new string[] {
                        "cpf",
                        "30390600822"});
            table9.AddRow(new string[] {
                        "email",
                        "contato@eduardopires.net.br"});
            table9.AddRow(new string[] {
                        "senha",
                        "Teste@123"});
            table9.AddRow(new string[] {
                        "senhaConfirmacao",
                        "Teste@124"});
#line 132
 testRunner.And("preenche os campos com os valores", ((string)(null)), table9, "E ");
#line 139
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 140
 testRunner.Then("Recebe uma mensagem de erro de que a senha estao diferentes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CadastroDeOrganizadorFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CadastroDeOrganizadorFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
